version: "0.5"

processes:
  p8i_app:
    command: ./scripts/start-p8i-app.sh
    availability:
      restart: on_failure
    readiness_probe:
      http_get:
        host: localhost
        port: 8080
      initial_delay_seconds: 10
      period_seconds: 5
