version: "0.5"

processes:
  p8i_app:
    command: bash -c "cd p8i_app && flutter pub get && flutter run -d web-server --web-port=10277 --web-hostname=0.0.0.0"
    availability:
      restart: "on_failure"
